name: default
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Format
      run: deno fmt --check
    - name: Lint
      run: deno lint
    - name: Run tests
      run: deno task test
